#!/bin/bash
LOCKSCREEN=~/.config/simplelock/lockscreen.png
LOCKSCREENRAW=~/.config/simplelock/lockscreen_raw
i3lock -t -i $LOCKSCREEN

# sleep 1 adds a small delay to prevent possible race conditions with suspend
sleep 1

# update in background
(
    case "$1" in
        xkcd_random)
            wget -qO- http://c.xkcd.com/random/comic| wget -O $LOCKSCREEN $(grep -Po '(?<=")https://imgs[^/]+/comics/[^"]+\.\w{3}')
            ;;
        xkcd_latest)
            wget -qO- http://xkcd.com/| wget -O $LOCKSCREEN $(grep -Po '(?<=")https://imgs[^/]+/comics/[^"]+\.\w{3}')
            ;;
        unsplash)
            wget https://source.unsplash.com/$2/?$3 -O $LOCKSCREENRAW
            convert $LOCKSCREENRAW $LOCKSCREEN
            ;;
        custom_fetch)
            wget $2 -O $LOCKSCREENRAW
            convert $LOCKSCREENRAW $LOCKSCREEN
            ;;
        custom_file)
            cp $2 $LOCKSCREENRAW
            convert $LOCKSCREENRAW $LOCKSCREEN
            ;;
        *)
            echo "== ! simplelock: missing or invalid argument ! =="
            echo "Try again with: xkcd_random | xkcd_latest | unsplash"
            exit 2
    esac

    convert $LOCKSCREEN ~/.config/simplelock/lock.png -gravity Center -composite $LOCKSCREEN 
    convert $LOCKSCREEN -gravity SouthEast -fill white -pointsize 40 -annotate +50+25 ''"$USER"'' $LOCKSCREEN;
)&
exit 0